-- Nagrik Sahayak: schemes table schema + seed data
-- Run this in Supabase Dashboard -> SQL Editor -> New query -> Run

drop table if exists schemes;

create table schemes (
  id text primary key,
  name text not null,
  category text,
  tags jsonb,
  description text,
  benefits text,
  documents jsonb,
  link text,
  criteria jsonb
);

insert into schemes (id, name, category, tags, description, benefits, documents, link, criteria) values
  ('pmkisan', 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)', 'Agriculture', '["farmer","kisan","agriculture","land","income support","cultivator"]'::jsonb, 'Income support of ₹6,000/year (in 3 installments) to landholding farmer families.', '₹6,000 per year, directly transferred in 3 installments of ₹2,000.', '["Aadhaar card","Land ownership records","Bank account (Aadhaar-linked)"]'::jsonb, 'https://pmkisan.gov.in', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["farmer"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('ayushman', 'Ayushman Bharat – PM Jan Arogya Yojana (PM-JAY)', 'Health', '["health","hospital","insurance","medical","treatment","senior citizen"]'::jsonb, 'Health cover of ₹5 lakh/year per family for secondary & tertiary hospitalization. Since 2024, ALL senior citizens aged 70+ are covered free, regardless of income — as a separate top-up on top of any existing family cover.', 'Cashless treatment up to ₹5,00,000 per family per year at empanelled hospitals. 70+ citizens get an additional personal ₹5,00,000 top-up, irrespective of income.', '["Aadhaar card","Ration card / family ID","Income certificate (if applicable, not needed for 70+)"]'::jsonb, 'https://pmjay.gov.in', '{"minAge":0,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('pmay-g', 'Pradhan Mantri Awas Yojana – Gramin (PMAY-G)', 'Housing', '["housing","home","house","pucca","shelter","rural","village"]'::jsonb, 'Direct financial assistance for rural houseless / kutcha-house families to build a pucca house.', '₹1.2 lakh (plain areas) / ₹1.3 lakh (hilly, difficult, IAP districts) direct assistance, plus MGNREGA labour convergence.', '["Aadhaar card","Income proof","Proof of no existing pucca house","Job card (if available)"]'::jsonb, 'https://pmayg.nic.in', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"rural"}'::jsonb),
  ('pmay-u', 'Pradhan Mantri Awas Yojana – Urban 2.0 (PMAY-U 2.0)', 'Housing', '["housing","home","house","pucca","shelter","urban","city","home loan"]'::jsonb, 'Interest subsidy on home loans for urban EWS/LIG/MIG families to buy, build, or rent affordable housing (2024–2029 scheme).', '4% interest subsidy, up to ₹1.8 lakh total, on the first ₹8 lakh of a home loan (loan up to ₹25 lakh, property value up to ₹35 lakh).', '["Aadhaar card","Income proof","Bank loan sanction letter","Property documents"]'::jsonb, 'https://pmaymis.gov.in', '{"minAge":18,"maxAge":null,"maxIncome":900000,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"urban"}'::jsonb),
  ('nsp', 'National Scholarship Portal Schemes', 'Education', '["student","scholarship","education","study","school","college"]'::jsonb, 'Merit-cum-means scholarships for school and college students from low-income families.', 'Tuition fee reimbursement and maintenance allowance (varies by scheme).', '["Aadhaar card","Income certificate","Previous mark sheet","Bank account"]'::jsonb, 'https://scholarships.gov.in', '{"minAge":5,"maxAge":35,"maxIncome":250000,"gender":"any","occupation":["student"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('ssy', 'Sukanya Samriddhi Yojana', 'Women & Child', '["girl child","daughter","savings","education","marriage"]'::jsonb, 'Small savings scheme for the financial security of a girl child, opened before age 10.', 'High interest rate savings account maturing at girl''s marriage/higher education age.', '["Girl child''s birth certificate","Aadhaar of parent/guardian","Bank/post office KYC"]'::jsonb, 'https://www.india.gov.in/spotlight/sukanya-samriddhi-yojana', '{"minAge":0,"maxAge":10,"maxIncome":null,"gender":"female","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('ujjwala', 'Pradhan Mantri Ujjwala Yojana', 'Women & Child', '["lpg","gas connection","cooking","women","bpl"]'::jsonb, 'Free LPG gas connection for women from BPL / low-income households.', 'Free LPG connection with first refill and stove support.', '["Aadhaar card","BPL / income proof","Bank account"]'::jsonb, 'https://pmuy.gov.in', '{"minAge":18,"maxAge":null,"maxIncome":200000,"gender":"female","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('apy', 'Atal Pension Yojana', 'Employment & Pension', '["pension","unorganized worker","old age","retirement"]'::jsonb, 'Guaranteed monthly pension (₹1,000–₹5,000) after age 60 for unorganized sector workers.', 'Fixed monthly pension after 60, based on contribution amount.', '["Aadhaar card","Bank account","Mobile number"]'::jsonb, 'https://npscra.nsdl.co.in/scheme-details.php', '{"minAge":18,"maxAge":40,"maxIncome":null,"gender":"any","occupation":["unorganized_worker","farmer","other"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('pmegp', 'PM Employment Generation Programme (PMEGP)', 'Employment & Pension', '["business","loan","entrepreneur","self employment","startup"]'::jsonb, 'Subsidized loans to set up new micro-enterprises for self-employment.', 'Bank loan with 15–35% government subsidy (margin money).', '["Aadhaar card","Project report","Educational certificate (8th pass min.)"]'::jsonb, 'https://www.kviconline.gov.in/pmegpeportal', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["entrepreneur","unemployed"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('standup', 'Stand-Up India', 'Employment & Pension', '["sc","st","women","business loan","entrepreneur"]'::jsonb, 'Bank loans between ₹10 lakh–₹1 crore for SC/ST and women entrepreneurs for greenfield enterprises.', 'Composite loan covering 75% of the project cost.', '["Aadhaar card","Caste certificate (if applicable)","Business plan"]'::jsonb, 'https://www.standupmitra.in', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["entrepreneur"],"disability":false,"category":"sc_st_or_women","sector":"any"}'::jsonb),
  ('nsap', 'National Social Assistance Programme (NSAP)', 'Employment & Pension', '["old age pension","widow pension","disability pension","bpl"]'::jsonb, 'Monthly pension support for elderly, widows, and persons with disability from BPL households.', '₹200/month (age 60–79) or ₹500/month (80+) from the Centre, topped up by states — average total around ₹1,000/month in most states.', '["Aadhaar card","Age/widow/disability proof","BPL card"]'::jsonb, 'https://nsap.nic.in', '{"minAge":18,"maxAge":null,"maxIncome":150000,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('pmmvy', 'PM Matru Vandana Yojana', 'Women & Child', '["pregnant","maternity","mother","child birth"]'::jsonb, 'Cash incentive for pregnant and lactating women — ₹5,000 for the first living child, plus ₹6,000 more if the second child is a girl.', '₹5,000 (in 2 installments) for the 1st child; additional ₹6,000 (1 installment) for a 2nd child if she''s a girl.', '["Aadhaar card","MCP card","Bank account"]'::jsonb, 'https://pmmvy.wcd.gov.in', '{"minAge":18,"maxAge":45,"maxIncome":null,"gender":"female","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('adip', 'ADIP Scheme (Assistance to Disabled Persons)', 'Disability', '["disability","divyang","aids","wheelchair","hearing aid"]'::jsonb, 'Free/subsidized assistive devices (wheelchairs, hearing aids, artificial limbs) for persons with disabilities.', 'Free or subsidized assistive aids and appliances.', '["Disability certificate","Aadhaar card","Income certificate"]'::jsonb, 'https://disabilityaffairs.gov.in', '{"minAge":0,"maxAge":null,"maxIncome":300000,"gender":"any","occupation":["any"],"disability":true,"category":"any","sector":"any"}'::jsonb),
  ('pmfby', 'PM Fasal Bima Yojana', 'Agriculture', '["farmer","crop insurance","agriculture","natural disaster"]'::jsonb, 'Crop insurance covering losses from natural calamities, pests, and disease.', 'Low-premium crop insurance with claim payout on crop loss.', '["Aadhaar card","Land records","Bank account","Sowing certificate"]'::jsonb, 'https://pmfby.gov.in', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["farmer"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('jandhan', 'PM Jan Dhan Yojana', 'Financial Inclusion', '["bank account","zero balance","financial inclusion"]'::jsonb, 'Zero-balance bank account with RuPay debit card and accident insurance cover.', 'Free bank account, RuPay card, ₹1–2 lakh accident insurance, overdraft facility.', '["Aadhaar card","Address proof"]'::jsonb, 'https://pmjdy.gov.in', '{"minAge":10,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('pmsby', 'PM Suraksha Bima Yojana', 'Insurance', '["accident insurance","low premium insurance"]'::jsonb, 'Accidental death/disability insurance cover of ₹2 lakh at ₹20/year premium (revised June 2025).', '₹2,00,000 cover for accidental death/full disability; ₹1,00,000 for partial disability.', '["Aadhaar card","Bank account"]'::jsonb, 'https://jansuraksha.gov.in', '{"minAge":18,"maxAge":70,"maxIncome":null,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('pmjjby', 'PM Jeevan Jyoti Bima Yojana', 'Insurance', '["life insurance","low premium insurance"]'::jsonb, 'Life insurance cover of ₹2 lakh on death by any cause, at ₹436/year premium (revised June 2025).', '₹2,00,000 life cover for the nominee.', '["Aadhaar card","Bank account"]'::jsonb, 'https://jansuraksha.gov.in', '{"minAge":18,"maxAge":50,"maxIncome":null,"gender":"any","occupation":["any"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('eshram', 'e-Shram Card', 'Employment & Pension', '["unorganized worker","daily wage","labour","registration","social security"]'::jsonb, 'National database registration for unorganized workers, unlocking social security benefits & accident insurance.', '₹2 lakh accident insurance cover, access to future welfare schemes.', '["Aadhaar card","Bank account","Mobile number"]'::jsonb, 'https://eshram.gov.in', '{"minAge":16,"maxAge":59,"maxIncome":null,"gender":"any","occupation":["unorganized_worker","farmer","other"],"disability":false,"category":"any","sector":"any"}'::jsonb),
  ('vishwakarma', 'PM Vishwakarma Yojana', 'Employment & Pension', '["artisan","craftsperson","carpenter","weaver","toolkit","traditional trade"]'::jsonb, 'Support for traditional artisans and craftspeople — toolkit incentive, skill training, and collateral-free loans.', 'Toolkit incentive up to ₹15,000, loans up to ₹3 lakh at concessional rates.', '["Aadhaar card","Trade proof / self-declaration"]'::jsonb, 'https://pmvishwakarma.gov.in', '{"minAge":18,"maxAge":null,"maxIncome":null,"gender":"any","occupation":["artisan"],"disability":false,"category":"any","sector":"any"}'::jsonb);
